### ISSUE TITLE
Compiled oimadmin.jar

### ISSUE THREAD

**Issue by srathore84** [shekhar-jha/OIMAdmin#19]
Do you mind in providing compiled jar file of oimadmin.jar also

**Comment by shekharjha-aurionpro** [comment]
Any specific reason why you can not use the release provided. Given that there are so many dependencies, releasing just OIMADmin.jar file may not be of much use.

**Comment by shekhar-jha** [comment]
Any specific reason why you can not use the release provided. Given that there are so many dependencies, releasing just OIMADmin.jar file may not be of much use.

**Comment by srathore84** [comment]
Due to imcomptibility with other products I have on my system, I cannot install JDK 1.8. So, seeing lot of compilation errors. Even if you provide compiled jar, I cannot execute it without jdk 1.8

So, need code that supports with JDK1.6/1.7 . I will try to convert this code compatable to jdk 1.6/1.7.
